import { Month } from "../../Types/User/calendar";

export const getUserActiveDates = (access_token: string): Date[] | null => {
  const dates: Date[] = [new Date(), new Date(), new Date()];

  return dates;
};

export const getUserOldDates = (access_token: string): Date[] | null => {
  const dates: Date[] = [new Date(), new Date(), new Date()];

  return dates;
};

export const getAvailableDates = (access_token: string): Month[] | null => {
  return dates;
};

const dates = [
  {
    name: "Junuary",
    days: [
      {
        date: "1",
        hours: [
          { hour: "09", minute: "00", active: false },
          { hour: "10", minute: "00", active: true },
          { hour: "11", minute: "00", active: false },
          { hour: "12", minute: "00", active: false },
          { hour: "13", minute: "00", active: true },
          { hour: "14", minute: "00", active: true },
          { hour: "15", minute: "00", active: false },
        ],
      },
      {
        date: "2",
        hours: [
          { hour: "09", minute: "00", active: true },
          { hour: "10", minute: "00", active: true },
          { hour: "11", minute: "00", active: true },
          { hour: "12", minute: "00", active: true },
          { hour: "13", minute: "00", active: true },
          { hour: "14", minute: "00", active: true },
          { hour: "15", minute: "00", active: true },
        ],
      },
      {
        date: "3",
        hours: [
          { hour: "09", minute: "00", active: true },
          { hour: "10", minute: "00", active: true },
          { hour: "11", minute: "00", active: true },
          { hour: "12", minute: "00", active: true },
          { hour: "13", minute: "00", active: true },
          { hour: "14", minute: "00", active: true },
          { hour: "15", minute: "00", active: true },
        ],
      },
      {
        date: "4",
        hours: [
          { hour: "09", minute: "00", active: true },
          { hour: "10", minute: "00", active: true },
          { hour: "11", minute: "00", active: true },
          { hour: "12", minute: "00", active: true },
          { hour: "13", minute: "00", active: true },
          { hour: "14", minute: "00", active: true },
          { hour: "15", minute: "00", active: true },
        ],
      },
      {
        date: "5",
        hours: [
          { hour: "09", minute: "00", active: true },
          { hour: "10", minute: "00", active: true },
          { hour: "11", minute: "00", active: true },
          { hour: "12", minute: "00", active: true },
          { hour: "13", minute: "00", active: true },
          { hour: "14", minute: "00", active: true },
          { hour: "15", minute: "00", active: true },
        ],
      },
      {
        date: "6",
        hours: [
          { hour: "09", minute: "00", active: true },
          { hour: "10", minute: "00", active: true },
          { hour: "11", minute: "00", active: true },
          { hour: "12", minute: "00", active: true },
          { hour: "13", minute: "00", active: true },
          { hour: "14", minute: "00", active: true },
          { hour: "15", minute: "00", active: true },
        ],
      },
      {
        date: "7",
        hours: [
          { hour: "09", minute: "00", active: true },
          { hour: "10", minute: "00", active: true },
          { hour: "11", minute: "00", active: true },
          { hour: "12", minute: "00", active: true },
          { hour: "13", minute: "00", active: true },
          { hour: "14", minute: "00", active: true },
          { hour: "15", minute: "00", active: true },
        ],
      },
      {
        date: "8",
        hours: [
          { hour: "09", minute: "00", active: true },
          { hour: "10", minute: "00", active: true },
          { hour: "11", minute: "00", active: true },
          { hour: "12", minute: "00", active: true },
          { hour: "13", minute: "00", active: true },
          { hour: "14", minute: "00", active: true },
          { hour: "15", minute: "00", active: true },
        ],
      },
      {
        date: "9",
        hours: [
          { hour: "09", minute: "00", active: true },
          { hour: "10", minute: "00", active: true },
          { hour: "11", minute: "00", active: true },
          { hour: "12", minute: "00", active: true },
          { hour: "13", minute: "00", active: true },
          { hour: "14", minute: "00", active: true },
          { hour: "15", minute: "00", active: true },
        ],
      },
      {
        date: "10",
        hours: [
          { hour: "09", minute: "00", active: true },
          { hour: "10", minute: "00", active: true },
          { hour: "11", minute: "00", active: true },
          { hour: "12", minute: "00", active: true },
          { hour: "13", minute: "00", active: true },
          { hour: "14", minute: "00", active: true },
          { hour: "15", minute: "00", active: true },
        ],
      },
      {
        date: "11",
        hours: [
          { hour: "09", minute: "00", active: true },
          { hour: "10", minute: "00", active: true },
          { hour: "11", minute: "00", active: true },
          { hour: "12", minute: "00", active: true },
          { hour: "13", minute: "00", active: true },
          { hour: "14", minute: "00", active: true },
          { hour: "15", minute: "00", active: true },
        ],
      },
      {
        date: "12",
        hours: [
          { hour: "09", minute: "00", active: true },
          { hour: "10", minute: "00", active: true },
          { hour: "11", minute: "00", active: true },
          { hour: "12", minute: "00", active: true },
          { hour: "13", minute: "00", active: true },
          { hour: "14", minute: "00", active: true },
          { hour: "15", minute: "00", active: true },
        ],
      },
      {
        date: "13",
        hours: [
          { hour: "09", minute: "00", active: true },
          { hour: "10", minute: "00", active: true },
          { hour: "11", minute: "00", active: true },
          { hour: "12", minute: "00", active: true },
          { hour: "13", minute: "00", active: true },
          { hour: "14", minute: "00", active: true },
          { hour: "15", minute: "00", active: true },
        ],
      },
      {
        date: "14",
        hours: [
          { hour: "09", minute: "00", active: true },
          { hour: "10", minute: "00", active: true },
          { hour: "11", minute: "00", active: true },
          { hour: "12", minute: "00", active: true },
          { hour: "13", minute: "00", active: true },
          { hour: "14", minute: "00", active: true },
          { hour: "15", minute: "00", active: true },
        ],
      },
      {
        date: "15",
        hours: [
          { hour: "09", minute: "00", active: true },
          { hour: "10", minute: "00", active: true },
          { hour: "11", minute: "00", active: true },
          { hour: "12", minute: "00", active: true },
          { hour: "13", minute: "00", active: true },
          { hour: "14", minute: "00", active: true },
          { hour: "15", minute: "00", active: true },
        ],
      },
      {
        date: "16",
        hours: [
          { hour: "09", minute: "00", active: true },
          { hour: "10", minute: "00", active: true },
          { hour: "11", minute: "00", active: true },
          { hour: "12", minute: "00", active: true },
          { hour: "13", minute: "00", active: true },
          { hour: "14", minute: "00", active: true },
          { hour: "15", minute: "00", active: true },
        ],
      },
      {
        date: "17",
        hours: [
          { hour: "09", minute: "00", active: true },
          { hour: "10", minute: "00", active: true },
          { hour: "11", minute: "00", active: true },
          { hour: "12", minute: "00", active: true },
          { hour: "13", minute: "00", active: true },
          { hour: "14", minute: "00", active: true },
          { hour: "15", minute: "00", active: true },
        ],
      },
      {
        date: "18",
        hours: [
          { hour: "09", minute: "00", active: true },
          { hour: "10", minute: "00", active: true },
          { hour: "11", minute: "00", active: true },
          { hour: "12", minute: "00", active: true },
          { hour: "13", minute: "00", active: true },
          { hour: "14", minute: "00", active: true },
          { hour: "15", minute: "00", active: true },
        ],
      },
      {
        date: "19",
        hours: [
          { hour: "09", minute: "00", active: true },
          { hour: "10", minute: "00", active: true },
          { hour: "11", minute: "00", active: true },
          { hour: "12", minute: "00", active: true },
          { hour: "13", minute: "00", active: true },
          { hour: "14", minute: "00", active: true },
          { hour: "15", minute: "00", active: true },
        ],
      },
      {
        date: "20",
        hours: [
          { hour: "09", minute: "00", active: true },
          { hour: "10", minute: "00", active: true },
          { hour: "11", minute: "00", active: true },
          { hour: "12", minute: "00", active: true },
          { hour: "13", minute: "00", active: true },
          { hour: "14", minute: "00", active: true },
          { hour: "15", minute: "00", active: true },
        ],
      },
      {
        date: "21",
        hours: [
          { hour: "09", minute: "00", active: true },
          { hour: "10", minute: "00", active: true },
          { hour: "11", minute: "00", active: true },
          { hour: "12", minute: "00", active: true },
          { hour: "13", minute: "00", active: true },
          { hour: "14", minute: "00", active: true },
          { hour: "15", minute: "00", active: true },
        ],
      },
      {
        date: "22",
        hours: [
          { hour: "09", minute: "00", active: true },
          { hour: "10", minute: "00", active: true },
          { hour: "11", minute: "00", active: true },
          { hour: "12", minute: "00", active: true },
          { hour: "13", minute: "00", active: true },
          { hour: "14", minute: "00", active: true },
          { hour: "15", minute: "00", active: true },
        ],
      },
      {
        date: "23",
        hours: [
          { hour: "09", minute: "00", active: true },
          { hour: "10", minute: "00", active: true },
          { hour: "11", minute: "00", active: true },
          { hour: "12", minute: "00", active: true },
          { hour: "13", minute: "00", active: true },
          { hour: "14", minute: "00", active: true },
          { hour: "15", minute: "00", active: true },
        ],
      },
      {
        date: "24",
        hours: [
          { hour: "09", minute: "00", active: true },
          { hour: "10", minute: "00", active: true },
          { hour: "11", minute: "00", active: true },
          { hour: "12", minute: "00", active: true },
          { hour: "13", minute: "00", active: true },
          { hour: "14", minute: "00", active: true },
          { hour: "15", minute: "00", active: true },
        ],
      },
      {
        date: "25",
        hours: [
          { hour: "09", minute: "00", active: true },
          { hour: "10", minute: "00", active: true },
          { hour: "11", minute: "00", active: true },
          { hour: "12", minute: "00", active: true },
          { hour: "13", minute: "00", active: true },
          { hour: "14", minute: "00", active: true },
          { hour: "15", minute: "00", active: true },
        ],
      },
      {
        date: "26",
        hours: [
          { hour: "09", minute: "00", active: true },
          { hour: "10", minute: "00", active: true },
          { hour: "11", minute: "00", active: true },
          { hour: "12", minute: "00", active: true },
          { hour: "13", minute: "00", active: true },
          { hour: "14", minute: "00", active: true },
          { hour: "15", minute: "00", active: true },
        ],
      },
      {
        date: "27",
        hours: [
          { hour: "09", minute: "00", active: true },
          { hour: "10", minute: "00", active: true },
          { hour: "11", minute: "00", active: true },
          { hour: "12", minute: "00", active: true },
          { hour: "13", minute: "00", active: true },
          { hour: "14", minute: "00", active: true },
          { hour: "15", minute: "00", active: true },
        ],
      },
      {
        date: "28",
        hours: [
          { hour: "09", minute: "00", active: true },
          { hour: "10", minute: "00", active: true },
          { hour: "11", minute: "00", active: true },
          { hour: "12", minute: "00", active: true },
          { hour: "13", minute: "00", active: true },
          { hour: "14", minute: "00", active: true },
          { hour: "15", minute: "00", active: true },
        ],
      },
      {
        date: "29",
        hours: [
          { hour: "09", minute: "00", active: true },
          { hour: "10", minute: "00", active: true },
          { hour: "11", minute: "00", active: true },
          { hour: "12", minute: "00", active: true },
          { hour: "13", minute: "00", active: true },
          { hour: "14", minute: "00", active: true },
          { hour: "15", minute: "00", active: true },
        ],
      },
      {
        date: "30",
        hours: [
          { hour: "09", minute: "00", active: true },
          { hour: "10", minute: "00", active: true },
          { hour: "11", minute: "00", active: true },
          { hour: "12", minute: "00", active: true },
          { hour: "13", minute: "00", active: true },
          { hour: "14", minute: "00", active: true },
          { hour: "15", minute: "00", active: true },
        ],
      },
      {
        date: "31",
        hours: [
          { hour: "09", minute: "00", active: true },
          { hour: "10", minute: "00", active: true },
          { hour: "11", minute: "00", active: true },
          { hour: "12", minute: "00", active: true },
          { hour: "13", minute: "00", active: true },
          { hour: "14", minute: "00", active: true },
          { hour: "15", minute: "00", active: true },
        ],
      },
    ],
  },
  {
    name: "February",
    days: [
      {
        date: "1",
        hours: [
          { hour: "09", minute: "00", active: true },
          { hour: "10", minute: "00", active: true },
          { hour: "11", minute: "00", active: true },
          { hour: "12", minute: "00", active: true },
          { hour: "13", minute: "00", active: true },
          { hour: "14", minute: "00", active: true },
          { hour: "15", minute: "00", active: true },
        ],
      },
      {
        date: "2",
        hours: [
          { hour: "09", minute: "00", active: true },
          { hour: "10", minute: "00", active: true },
          { hour: "11", minute: "00", active: true },
          { hour: "12", minute: "00", active: true },
          { hour: "13", minute: "00", active: true },
          { hour: "14", minute: "00", active: true },
          { hour: "15", minute: "00", active: true },
        ],
      },
      {
        date: "3",
        hours: [
          { hour: "09", minute: "00", active: true },
          { hour: "10", minute: "00", active: true },
          { hour: "11", minute: "00", active: true },
          { hour: "12", minute: "00", active: true },
          { hour: "13", minute: "00", active: true },
          { hour: "14", minute: "00", active: true },
          { hour: "15", minute: "00", active: true },
        ],
      },
      {
        date: "4",
        hours: [
          { hour: "09", minute: "00", active: true },
          { hour: "10", minute: "00", active: true },
          { hour: "11", minute: "00", active: true },
          { hour: "12", minute: "00", active: true },
          { hour: "13", minute: "00", active: true },
          { hour: "14", minute: "00", active: true },
          { hour: "15", minute: "00", active: true },
        ],
      },
      {
        date: "5",
        hours: [
          { hour: "09", minute: "00", active: true },
          { hour: "10", minute: "00", active: true },
          { hour: "11", minute: "00", active: true },
          { hour: "12", minute: "00", active: true },
          { hour: "13", minute: "00", active: true },
          { hour: "14", minute: "00", active: true },
          { hour: "15", minute: "00", active: true },
        ],
      },
      {
        date: "6",
        hours: [
          { hour: "09", minute: "00", active: true },
          { hour: "10", minute: "00", active: true },
          { hour: "11", minute: "00", active: true },
          { hour: "12", minute: "00", active: true },
          { hour: "13", minute: "00", active: true },
          { hour: "14", minute: "00", active: true },
          { hour: "15", minute: "00", active: true },
        ],
      },
      {
        date: "7",
        hours: [
          { hour: "09", minute: "00", active: true },
          { hour: "10", minute: "00", active: true },
          { hour: "11", minute: "00", active: true },
          { hour: "12", minute: "00", active: true },
          { hour: "13", minute: "00", active: true },
          { hour: "14", minute: "00", active: true },
          { hour: "15", minute: "00", active: true },
        ],
      },
      {
        date: "8",
        hours: [
          { hour: "09", minute: "00", active: true },
          { hour: "10", minute: "00", active: true },
          { hour: "11", minute: "00", active: true },
          { hour: "12", minute: "00", active: true },
          { hour: "13", minute: "00", active: true },
          { hour: "14", minute: "00", active: true },
          { hour: "15", minute: "00", active: true },
        ],
      },
      {
        date: "9",
        hours: [
          { hour: "09", minute: "00", active: true },
          { hour: "10", minute: "00", active: true },
          { hour: "11", minute: "00", active: true },
          { hour: "12", minute: "00", active: true },
          { hour: "13", minute: "00", active: true },
          { hour: "14", minute: "00", active: true },
          { hour: "15", minute: "00", active: true },
        ],
      },
      {
        date: "10",
        hours: [
          { hour: "09", minute: "00", active: true },
          { hour: "10", minute: "00", active: true },
          { hour: "11", minute: "00", active: true },
          { hour: "12", minute: "00", active: true },
          { hour: "13", minute: "00", active: true },
          { hour: "14", minute: "00", active: true },
          { hour: "15", minute: "00", active: true },
        ],
      },
      {
        date: "11",
        hours: [
          { hour: "09", minute: "00", active: true },
          { hour: "10", minute: "00", active: true },
          { hour: "11", minute: "00", active: true },
          { hour: "12", minute: "00", active: true },
          { hour: "13", minute: "00", active: true },
          { hour: "14", minute: "00", active: true },
          { hour: "15", minute: "00", active: true },
        ],
      },
      {
        date: "12",
        hours: [
          { hour: "09", minute: "00", active: true },
          { hour: "10", minute: "00", active: true },
          { hour: "11", minute: "00", active: true },
          { hour: "12", minute: "00", active: true },
          { hour: "13", minute: "00", active: true },
          { hour: "14", minute: "00", active: true },
          { hour: "15", minute: "00", active: true },
        ],
      },
      {
        date: "13",
        hours: [
          { hour: "09", minute: "00", active: true },
          { hour: "10", minute: "00", active: true },
          { hour: "11", minute: "00", active: true },
          { hour: "12", minute: "00", active: true },
          { hour: "13", minute: "00", active: true },
          { hour: "14", minute: "00", active: true },
          { hour: "15", minute: "00", active: true },
        ],
      },
      {
        date: "14",
        hours: [
          { hour: "09", minute: "00", active: true },
          { hour: "10", minute: "00", active: true },
          { hour: "11", minute: "00", active: true },
          { hour: "12", minute: "00", active: true },
          { hour: "13", minute: "00", active: true },
          { hour: "14", minute: "00", active: true },
          { hour: "15", minute: "00", active: true },
        ],
      },
      {
        date: "15",
        hours: [
          { hour: "09", minute: "00", active: true },
          { hour: "10", minute: "00", active: true },
          { hour: "11", minute: "00", active: true },
          { hour: "12", minute: "00", active: true },
          { hour: "13", minute: "00", active: true },
          { hour: "14", minute: "00", active: true },
          { hour: "15", minute: "00", active: true },
        ],
      },
      {
        date: "16",
        hours: [
          { hour: "09", minute: "00", active: true },
          { hour: "10", minute: "00", active: true },
          { hour: "11", minute: "00", active: true },
          { hour: "12", minute: "00", active: true },
          { hour: "13", minute: "00", active: true },
          { hour: "14", minute: "00", active: true },
          { hour: "15", minute: "00", active: true },
        ],
      },
      {
        date: "17",
        hours: [
          { hour: "09", minute: "00", active: true },
          { hour: "10", minute: "00", active: true },
          { hour: "11", minute: "00", active: true },
          { hour: "12", minute: "00", active: true },
          { hour: "13", minute: "00", active: true },
          { hour: "14", minute: "00", active: true },
          { hour: "15", minute: "00", active: true },
        ],
      },
      {
        date: "18",
        hours: [
          { hour: "09", minute: "00", active: true },
          { hour: "10", minute: "00", active: true },
          { hour: "11", minute: "00", active: true },
          { hour: "12", minute: "00", active: true },
          { hour: "13", minute: "00", active: true },
          { hour: "14", minute: "00", active: true },
          { hour: "15", minute: "00", active: true },
        ],
      },
      {
        date: "19",
        hours: [
          { hour: "09", minute: "00", active: true },
          { hour: "10", minute: "00", active: true },
          { hour: "11", minute: "00", active: true },
          { hour: "12", minute: "00", active: true },
          { hour: "13", minute: "00", active: true },
          { hour: "14", minute: "00", active: true },
          { hour: "15", minute: "00", active: true },
        ],
      },
      {
        date: "20",
        hours: [
          { hour: "09", minute: "00", active: true },
          { hour: "10", minute: "00", active: true },
          { hour: "11", minute: "00", active: true },
          { hour: "12", minute: "00", active: true },
          { hour: "13", minute: "00", active: true },
          { hour: "14", minute: "00", active: true },
          { hour: "15", minute: "00", active: true },
        ],
      },
      {
        date: "21",
        hours: [
          { hour: "09", minute: "00", active: true },
          { hour: "10", minute: "00", active: true },
          { hour: "11", minute: "00", active: true },
          { hour: "12", minute: "00", active: true },
          { hour: "13", minute: "00", active: true },
          { hour: "14", minute: "00", active: true },
          { hour: "15", minute: "00", active: true },
        ],
      },
      {
        date: "22",
        hours: [
          { hour: "09", minute: "00", active: true },
          { hour: "10", minute: "00", active: true },
          { hour: "11", minute: "00", active: true },
          { hour: "12", minute: "00", active: true },
          { hour: "13", minute: "00", active: true },
          { hour: "14", minute: "00", active: true },
          { hour: "15", minute: "00", active: true },
        ],
      },
      {
        date: "23",
        hours: [
          { hour: "09", minute: "00", active: true },
          { hour: "10", minute: "00", active: true },
          { hour: "11", minute: "00", active: true },
          { hour: "12", minute: "00", active: true },
          { hour: "13", minute: "00", active: true },
          { hour: "14", minute: "00", active: true },
          { hour: "15", minute: "00", active: true },
        ],
      },
      {
        date: "24",
        hours: [
          { hour: "09", minute: "00", active: true },
          { hour: "10", minute: "00", active: true },
          { hour: "11", minute: "00", active: true },
          { hour: "12", minute: "00", active: true },
          { hour: "13", minute: "00", active: true },
          { hour: "14", minute: "00", active: true },
          { hour: "15", minute: "00", active: true },
        ],
      },
      {
        date: "25",
        hours: [
          { hour: "09", minute: "00", active: true },
          { hour: "10", minute: "00", active: true },
          { hour: "11", minute: "00", active: true },
          { hour: "12", minute: "00", active: true },
          { hour: "13", minute: "00", active: true },
          { hour: "14", minute: "00", active: true },
          { hour: "15", minute: "00", active: true },
        ],
      },
      {
        date: "26",
        hours: [
          { hour: "09", minute: "00", active: true },
          { hour: "10", minute: "00", active: true },
          { hour: "11", minute: "00", active: true },
          { hour: "12", minute: "00", active: true },
          { hour: "13", minute: "00", active: true },
          { hour: "14", minute: "00", active: true },
          { hour: "15", minute: "00", active: true },
        ],
      },
      {
        date: "27",
        hours: [
          { hour: "09", minute: "00", active: true },
          { hour: "10", minute: "00", active: true },
          { hour: "11", minute: "00", active: true },
          { hour: "12", minute: "00", active: true },
          { hour: "13", minute: "00", active: true },
          { hour: "14", minute: "00", active: true },
          { hour: "15", minute: "00", active: true },
        ],
      },
      {
        date: "28",
        hours: [
          { hour: "09", minute: "00", active: true },
          { hour: "10", minute: "00", active: true },
          { hour: "11", minute: "00", active: true },
          { hour: "12", minute: "00", active: true },
          { hour: "13", minute: "00", active: true },
          { hour: "14", minute: "00", active: true },
          { hour: "15", minute: "00", active: true },
        ],
      },
    ],
  },
];
