FROM node:12.16.3-alpine as build

WORKDIR /app

COPY ["./package.json", "./yarn.lock", "./"]
RUN yarn install
COPY . ./

RUN yarn build

FROM nginx:stable-alpine
COPY --from=build /app/build /usr/share/nginx/html
COPY nginx/nginx.conf /etc/nginx/conf.d/default.conf

EXPOSE 80

CMD ["nginx", "-g", "daemon off;"]